DRIVE_LEFT_FRONT = 11
DRIVE_LEFT_BACK = 12
DRIVE_RIGHT_FRONT = 18
DRIVE_RIGHT_BACK = 17

SOLENOID_LIFT = 0
SOLENOID_SHIFTER = 1

INTAKE_LEFT_MOTOR = 13
INTAKE_RIGHT_MOTOR = 16

JOYSTICK_PORT = 0

JOYSTICK_INTAKE_IN_BUTTON = 8
JOYSTICK_INTAKE_OUT_BUTTON = 9